import { ModelResponseDto } from "@/types/model/model.wrapper.type";

export const MOCK_MODEL_RESULT: ModelResponseDto = {
  tourspots: [
    {
      id: 1,
      placeId: 1,
      name: "서울숲",
      latitude: 37.5444,
      longitude: 127.0374,
      address: "서울특별시 성동구 뚝섬로 273",
      description: "도심 속에서 자연을 즐길 수 있는 대형 시민공원",
      duration: "2~3시간",
      images: ["https://images.unsplash.com/photo-1549693578-d683be217e58"],
      keywords: ["공원", "자연", "산책", "휴식"],
      category: "tourspot",
      province: "서울",
    },
    {
      id: 2,
      placeId: 2,
      name: "뚝섬 한강공원",
      latitude: 37.5292,
      longitude: 127.0668,
      address: "서울특별시 성동구/인근 뚝섬 한강공원",
      description: "한강을 따라 산책과 피크닉을 즐기기 좋은 장소",
      duration: "2~3시간",
      images: ["https://images.unsplash.com/photo-1519985176271-adb1088fa94c"],
      keywords: ["한강", "피크닉", "야경", "자전거"],
      category: "tourspot",
      province: "서울",
    },
    {
      id: 3,
      placeId: 3,
      name: "성수 연무장길",
      latitude: 37.5449,
      longitude: 127.0553,
      address: "서울특별시 성동구 성수동2가",
      description: "카페·편집숍이 모여 있는 트렌디한 거리",
      duration: "1~2시간",
      images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5"],
      keywords: ["성수", "산책", "핫플"],
      category: "tourspot",
      province: "서울",
    },
    {
      id: 4,
      placeId: 4,
      name: "성수대교 북단 산책로",
      latitude: 37.5382,
      longitude: 127.0449,
      address: "서울특별시 성동구 성수동1가",
      description: "강변을 따라 걷기 좋은 산책 구간",
      duration: "1~2시간",
      images: ["https://images.unsplash.com/photo-1549693578-d683be217e58"],
      keywords: ["산책", "강변", "뷰"],
      category: "tourspot",
      province: "서울",
    },
  ],

  restaurants: [
    {
      id: 101,
      placeId: 101,
      name: "성수 로컬 국밥집",
      latitude: 37.5461,
      longitude: 127.0536,
      address: "서울특별시 성동구 성수동2가",
      description: "든든하게 한 끼 하기 좋은 국밥집",
      duration: "1~2시간",
      images: ["https://images.unsplash.com/photo-1519985176271-adb1088fa94c"],
      keywords: ["국밥", "로컬", "한식"],
      category: "restaurant",
      province: "서울",
    },
    {
      id: 102,
      placeId: 102,
      name: "뚝섬 파스타 바",
      latitude: 37.5412,
      longitude: 127.061,
      address: "서울특별시 성동구 성수동1가",
      description: "가볍게 즐기기 좋은 이탈리안",
      duration: "1~2시간",
      images: ["https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba"],
      keywords: ["파스타", "데이트", "분위기"],
      category: "restaurant",
      province: "서울",
    },
  ],

  cafes: [
    {
      id: 201,
      placeId: 201,
      name: "성수 로스터리 카페",
      latitude: 37.5459,
      longitude: 127.0547,
      address: "서울특별시 성동구 성수동2가",
      description: "로스팅 향이 좋은 카페",
      duration: "1~2시간",
      images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5"],
      keywords: ["로스터리", "커피", "성수"],
      category: "cafe",
      province: "서울",
    },
    {
      id: 202,
      placeId: 202,
      name: "서울숲 디저트 카페",
      latitude: 37.5451,
      longitude: 127.0359,
      address: "서울특별시 성동구 성수동1가",
      description: "산책 후 들르기 좋은 디저트 카페",
      duration: "1~2시간",
      images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5"],
      keywords: ["디저트", "카페", "휴식"],
      category: "cafe",
      province: "서울",
    },
  ],
};
