import { ModelResponseDto } from "@/types/model/model.type";

export const TEMP_MODEL_RESULTS: ModelResponseDto[] = [
  {
    tourspots: [
      {
        id: 11,
        placeId: 11,
        name: "성수 연무장길",
        latitude: 37.5449,
        longitude: 127.0553,
        address: "서울 성동구 성수동2가",
        description: "카페와 편집숍이 모인 거리",
        duration: "1~2시간",
        images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5"],
        keywords: ["성수", "산책", "핫플"],
        category: "tourspot",
        province: "서울",
      },
      {
        id: 12,
        placeId: 12,
        name: "서울숲",
        latitude: 37.5444,
        longitude: 127.0374,
        address: "서울 성동구",
        description: "도심 속 자연 공원",
        duration: "2~3시간",
        images: ["https://images.unsplash.com/photo-1549693578-d683be217e58"],
        keywords: ["공원", "자연"],
        category: "tourspot",
        province: "서울",
      },
    ],
    restaurants: [
      {
        id: 111,
        placeId: 111,
        name: "성수 수제버거",
        latitude: 37.5453,
        longitude: 127.0561,
        address: "서울 성동구",
        description: "육즙 가득 수제버거",
        duration: "1시간",
        images: ["https://images.unsplash.com/photo-1550547660-d9450f859349"],
        keywords: ["버거", "성수"],
        category: "restaurant",
        province: "서울",
      },
    ],
    cafes: [
      {
        id: 211,
        placeId: 211,
        name: "성수 로스터리",
        latitude: 37.5459,
        longitude: 127.0547,
        address: "서울 성동구",
        description: "로스팅 카페",
        duration: "1~2시간",
        images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5"],
        keywords: ["커피", "로스터리"],
        category: "cafe",
        province: "서울",
      },
    ],
  },

  {
    tourspots: [
      {
        id: 21,
        placeId: 21,
        name: "해운대 해변",
        latitude: 35.1587,
        longitude: 129.1604,
        address: "부산 해운대구",
        description: "바다 산책로",
        duration: "1~2시간",
        images: ["https://images.unsplash.com/photo-1549693578-d683be217e58"],
        keywords: ["바다", "산책"],
        category: "tourspot",
        province: "부산",
      },
    ],
    restaurants: [
      {
        id: 121,
        placeId: 121,
        name: "해운대 국밥집",
        latitude: 35.1596,
        longitude: 129.1618,
        address: "부산 해운대구",
        description: "로컬 국밥",
        duration: "1~2시간",
        images: [
          "https://images.unsplash.com/photo-1516685018646-549d72f40539",
        ],
        keywords: ["국밥", "로컬"],
        category: "restaurant",
        province: "부산",
      },
    ],
    cafes: [
      {
        id: 221,
        placeId: 221,
        name: "광안리 오션뷰 카페",
        latitude: 35.1526,
        longitude: 129.1198,
        address: "부산 수영구",
        description: "바다 보이는 카페",
        duration: "1~2시간",
        images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5"],
        keywords: ["오션뷰", "카페"],
        category: "cafe",
        province: "부산",
      },
    ],
  },
];
